# Generated by Django 5.0.4 on 2024-05-11 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Банк',
                'verbose_name_plural': 'Банки',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='DiaryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Страница параметров',
                'verbose_name_plural': 'Параметры',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PlanCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('commission', models.BooleanField()),
                ('period', models.BooleanField()),
                ('lower_limit', models.BooleanField()),
                ('upper_limit', models.BooleanField()),
                ('transfer_limit', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Категория плана',
                'verbose_name_plural': 'Категории планов',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='TransactionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure', models.IntegerField()),
                ('destination', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Транзакция',
                'verbose_name_plural': 'Транзакции',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PersonModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('surname', models.CharField(max_length=50, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('passport', models.IntegerField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ClientModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('passport', models.IntegerField()),
                ('precarious', models.BooleanField()),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.bankmodel')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.personmodel')),
            ],
            options={
                'verbose_name': 'Аккаунт',
                'verbose_name_plural': 'Аккаунты',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PlanModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('commission', models.DecimalField(decimal_places=6, max_digits=8)),
                ('increased_commission', models.DecimalField(decimal_places=6, max_digits=8)),
                ('period', models.IntegerField()),
                ('decreased_period', models.IntegerField()),
                ('lower_limit', models.DecimalField(decimal_places=2, max_digits=14)),
                ('decreased_lower_limit', models.DecimalField(decimal_places=2, max_digits=14)),
                ('upper_limit', models.DecimalField(decimal_places=2, max_digits=14)),
                ('decreased_upper_limit', models.DecimalField(decimal_places=2, max_digits=14)),
                ('transfer_limit', models.DecimalField(decimal_places=2, max_digits=14)),
                ('decreased_transfer_limit', models.DecimalField(decimal_places=2, max_digits=14)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.bankmodel')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.plancategorymodel')),
            ],
            options={
                'verbose_name': 'Тарифный план',
                'verbose_name_plural': 'Тарифные планы',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='AccountModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opened', models.BooleanField()),
                ('money', models.DecimalField(decimal_places=2, max_digits=14)),
                ('transfer', models.DecimalField(decimal_places=2, max_digits=14)),
                ('freeze_date', models.IntegerField()),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.bankmodel')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.clientmodel')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.planmodel')),
            ],
            options={
                'verbose_name': 'Счет',
                'verbose_name_plural': 'Счета',
                'ordering': ['-id'],
            },
        ),
    ]
